### ISSUE TITLE
not found maximum_spanning_tree

### ISSUE THREAD

**Issue by lephong** [rycolab/spanningtrees#1]
In the source code, `spanningtrees` is replaced by `maximum_spanning_tree` everywhere. E.g. in mst.py:

```python
from maximum_spanning_tree.edge_priority_queue import EdgePriorityQueue
```

rather than 
```python
from spanningtrees.edge_priority_queue import EdgePriorityQueue
```

Should it be a problem? (I got "not found `edge_priority_queue`" error)

**Comment by ranzmigrod** [comment]
Hi,

Thank you for pointing this out! My apologies, this should now be fixed with [the latest commit](https://github.com/rycolab/spanningtrees/commit/5a90e5ba93264175a8f93996c2d41bb91f7f2656).
