### ISSUE TITLE
ERROR: No matching distribution found for arsenal

### ISSUE THREAD

**Issue by qroam** [rycolab/spanningtrees#2]
When `pip install` the package, always met these 2 errors:

> ERROR: Could not find a version that satisfies the requirement arsenal (from spanningtrees) (from versions: none)
> ERROR: No matching distribution found for arsenal

Python version 3.9.0 and 3.6.0 all failed
I wonder if this _arsenal_ is the package from https://github.com/timvieira/arsenal
or there could be something wrong with my environment?

By the way, maybe the **spanningtree** in the **README.md** sholud be changed into **spanningtrees**

> git clone https://github.com/rycolab/spanningtree
> cd spanningtree
> pip install -e .

**Comment by ranzmigrod** [comment]
That is correct, you need to install the arsenal package from https://github.com/timvieira/arsenal
